/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.User;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;

/**
 *
 * @author vincent
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel() {
        initComponents();
        setupComponents();
    }
    
    private void setupComponents(){
        FirstNameTextField.setEnabled(false);
        LastNameTextField.setEnabled(false);
        AgeSpinner.setEnabled(false);
        PhoneFormattedTextField.setEnabled(false);
        EmailFormattedTextField.setEnabled(false);
        ContinentComboBox.setEnabled(false);
        DobTextField.setEnabled(false);

        HobbyTextArea.setEditable(false);
        Color grayBg = new Color(240, 240, 240);
        FirstNameTextField.setBackground(grayBg);
        LastNameTextField.setBackground(grayBg);
        PhoneFormattedTextField.setBackground(grayBg);
        EmailFormattedTextField.setBackground(grayBg);
        HobbyTextArea.setBackground(grayBg);
        if (photoDisplayLabel != null){
            photoDisplayLabel.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            photoDisplayLabel.setHorizontalAlignment(SwingConstants.CENTER);
            photoDisplayLabel.setText("No Photo");
        }
    }
public void displayUser(User user){
    if (user == null){
        clearFields();
        return;
    }

FirstNameTextField.setText(user.getFirstName());
LastNameTextField.setText(user.getLastName());
AgeSpinner.setValue(user.getAge());
PhoneFormattedTextField.setText(user.getPhone());
EmailFormattedTextField.setText(user.getEmail());
ContinentComboBox.setSelectedItem(user.getContinent());

HobbyTextArea.setText(user.getHobby());
if (user.getDob() != null) {
    java.text.SimpleDateFormat sdf =
        new java.text.SimpleDateFormat("yyyy-MM-dd");
    DobTextField.setText(sdf.format(user.getDob()));
}


if (user.getPhoto()!=null&& photoDisplayLabel != null){
photoDisplayLabel.setIcon(new ImageIcon(user.getPhoto()));
photoDisplayLabel.setText("");

}else if (photoDisplayLabel != null){
    photoDisplayLabel.setIcon(null);
    photoDisplayLabel.setText("No Photo");
    
}
}
private void clearFields(){
    FirstNameTextField.setText("");
    LastNameTextField.setText("");
    AgeSpinner.setValue(0);
    PhoneFormattedTextField.setText("");
    EmailFormattedTextField.setText("");
    ContinentComboBox.setSelectedIndex(0);
    HobbyTextArea.setText("");

 if (photoDisplayLabel != null){
     photoDisplayLabel.setIcon(null);
    photoDisplayLabel.setText("No Photo");
 }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DetailsLabel = new javax.swing.JLabel();
        FisrtNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        HobbyLabel = new javax.swing.JLabel();
        ContinentLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        EmailFormattedTextField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        HobbyTextArea = new javax.swing.JTextArea();
        ContinentComboBox = new javax.swing.JComboBox<>();
        AgeSpinner = new javax.swing.JSpinner();
        PhoneFormattedTextField = new javax.swing.JFormattedTextField();
        photoDisplayLabel = new javax.swing.JLabel();
        DobTextField = new javax.swing.JTextField();

        DetailsLabel.setText("Student Details");

        FisrtNameLabel.setText("Frist Name:");

        LastNameLabel.setText("Last Name:");

        AgeLabel.setText("Age:");

        EmailLabel.setText("Email:");

        PhoneLabel.setText("Phone:");

        HobbyLabel.setText("Hobby:");

        ContinentLabel.setText("Continent:");

        FirstNameTextField.addActionListener(this::FirstNameTextFieldActionPerformed);

        HobbyTextArea.setColumns(20);
        HobbyTextArea.setRows(5);
        jScrollPane1.setViewportView(HobbyTextArea);

        ContinentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "South America", "North America", "Europe", "Asian", "Africa", "Australia", "Antartica" }));

        photoDisplayLabel.setText("Photo Display");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailLabel)
                            .addComponent(ContinentLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LastNameLabel)
                                            .addComponent(AgeLabel))
                                        .addComponent(FisrtNameLabel))
                                    .addComponent(PhoneLabel))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContinentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(PhoneFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                        .addComponent(EmailFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LastNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(DobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(HobbyLabel)
                                .addGap(89, 89, 89)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(DetailsLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(photoDisplayLabel)))
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(DetailsLabel)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FisrtNameLabel)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeLabel))
                .addGap(18, 18, 18)
                .addComponent(DobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel)
                    .addComponent(PhoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContinentLabel)
                    .addComponent(ContinentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HobbyLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(photoDisplayLabel)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JSpinner AgeSpinner;
    private javax.swing.JComboBox<String> ContinentComboBox;
    private javax.swing.JLabel ContinentLabel;
    private javax.swing.JLabel DetailsLabel;
    private javax.swing.JTextField DobTextField;
    private javax.swing.JFormattedTextField EmailFormattedTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel FisrtNameLabel;
    private javax.swing.JLabel HobbyLabel;
    private javax.swing.JTextArea HobbyTextArea;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JFormattedTextField PhoneFormattedTextField;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel photoDisplayLabel;
    // End of variables declaration//GEN-END:variables

}